
baseURL = "https://TheAutomatingMrLynch.github.io/hugo-poc"
languageCode = "en-us"
title = "My Hugo Site"

[[module.imports]]
path = "github.com/nunocoracao/blowfish/v2"

# Layout settings for all posts
[cascade]
  [[cascade._target]]
    path = "/posts/**"
    type = "article"    # or "page", "projects" depending on your preference

# Navigation Menu
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "About"
url = "/about/"
weight = 30
