defaultAppearance = "light"  # "light", "dark", or "auto"

[assets]
customCSS = [
    "css/custom.css"
]

[author]
name = "Yao Ming"
email = "your.mother@example.com"
links = [
    { email = "mailto:your.mother@example.com" },
]


[header]
layout = "basic" # "basic", "hamburger", "hybrid"


[search]
showInHeader = true

[footer]
showCopyright = true
showThemeAttribution = false

[homepage]
homepageImage = "img/happy.png"
layout = "card" # "page", "profile", "hero", "card", "background"
showRecent = true
homepage.cardView = true
homepage.layoutBackgroundBlur = true

# Article styling
[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"  # "basic", "big", "background"
showBreadcrumbs = true
showTableOfContents = true
showWordCount = true
showSummary = true
sharingLinks = ["linkedin", "twitter", "reddit", "pinterest", "facebook"]