defaultAppearance = "light"  # "light", "dark", or "auto"
defaultBackgroundImage = "img/happy.png" # used as default for background images

[assets]
customCSS = [
    "css/custom.css"
]

[author]
name = "Yao Ming"
email = "your.mother@example.com"
links = [
    { email = "mailto:your.mother@example.com" },
]


[homepage]
layout = "card" # "page", "profile", "hero", "card", "background"
homepageImage = "img/happy.png" # used in: hero and card
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true # only used when layout equals background

[header]
layout = "fixed" # "basic", "fixed", "fixed-fill", and "fixed-fill-blur"

[footer]
showCopyright = true
showThemeAttribution = false

[search]
showInHeader = true

# Article styling
[article]
showDate = true
showDateUpdated = false
showViews = false
showLikes = false
showAuthor = true
showHero = true
heroStyle = "basic"  # "basic", "big", "background"
showBreadcrumbs = true
showTableOfContents = true
showWordCount = true
showSummary = true
showRelatedContent = true
relatedContentLimit = 3
sharingLinks = ["youtube", "facebook"]

[list]
showCards = true
groupByYear = false
cardView = true
