defaultAppearance = "light"  # "light", "dark", or "auto"

[assets]
customCSS = [
    "css/custom.css"
]

[author]
name = "Yao Ming"
email = "your.mother@example.com"
links = [
    { email = "mailto:your.mother@example.com" },
]


[header]
layout = "basic" # "basic", "hamburger", "hybrid"


[search]
showInHeader = true

[footer]
showCopyright = true
#showThemeAttribution = true

[homepage]
layout = "hero" # "page", "profile", "hero", "card", "background"
homepageImage = "img/yao-ming.png"  # Optional hero image
showRecent = false

# Article styling
[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"  # "basic", "big", "background"
showBreadcrumbs = true
showTableOfContents = true
showWordCount = true
showSummary = true
sharingLinks = ["linkedin", "twitter", "reddit", "pinterest", "facebook"]