[assets]
customCSS = [
    "assets/css/blowfish/custom.css",
#    "css/blowfish/overrides.css"
]

# Blowfish-specific author configuration
[author]
name = "Your Name"
email = "your.email@example.com"
links = [
    { email = "mailto:your.email@example.com" },
]

# Blowfish theme parameters
colorScheme = "blowfish"  # or "avocado", "fire", "ocean", etc.
defaultAppearance = "light"  # "light", "dark", or "auto"

[header]
layout = "basic" # "basic", "hamburger", "hybrid"

# Search configuration (Blowfish-specific)
[search]
showInHeader = true

[footer]
showCopyright = true
#showThemeAttribution = true

[homepage]
layout = "page" # "page", "profile", "hero", "card", "background"
homepageImage = "img/hero.jpg"  # Optional hero image
showRecent = false

# Article styling
[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"  # "basic", "big", "background"
showBreadcrumbs = true
showTableOfContents = true
showWordCount = true
showSummary = true
sharingLinks = ["linkedin", "twitter", "reddit", "pinterest", "facebook"]