[assets]
customCSS = [
    "css/custom.css"
]

env = "production"
defaultTheme = "auto" # "light", "dark", "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[socialIcons]]
name = "github"
url = "https://github.com/"

# PaperMod search configuration
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.0
minMatchCharLength = 2
keys = ["title", "permalink", "summary", "content"]